version: '3.8'

services:
  xelatex-pdf-service:
    build:
      context: .
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - texlive-cache:/root/.cache/texlive
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  texlive-cache:
    driver: local 